/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Marcos
 */
public class Vista_nSeco extends javax.swing.JFrame {

    /**
     * Creates new form VistaCal
     */
    public Vista_nSeco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMetros = new javax.swing.JTextField();
        btnJuntaTomada = new javax.swing.JButton();
        selectorJuntaTomada = new javax.swing.JLabel();
        btnDesmontable = new javax.swing.JButton();
        selectorDesmontable = new javax.swing.JLabel();
        btnSimple = new javax.swing.JButton();
        selectorSimple = new javax.swing.JLabel();
        btnDoble = new javax.swing.JButton();
        selectorDoble = new javax.swing.JLabel();
        btnMuros = new javax.swing.JButton();
        selectorMuros = new javax.swing.JLabel();
        btnCielorrasos = new javax.swing.JButton();
        selectorCielorrasos = new javax.swing.JLabel();
        btnPlaca = new javax.swing.JButton();
        selectorPlaca = new javax.swing.JLabel();
        btnMinim = new javax.swing.JButton();
        btnCerrar2 = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        btnToPDF = new javax.swing.JButton();
        btnPresupuesto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPresupuesto = new javax.swing.JTextArea();
        lblPlaca = new javax.swing.JLabel();
        chkDesperdicio = new javax.swing.JCheckBox();
        lblFirma = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblUnidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnConfiguracion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(840, 519));
        setPreferredSize(new java.awt.Dimension(840, 519));
        setResizable(false);
        setSize(new java.awt.Dimension(840, 519));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setFocusCycleRoot(true);
        jPanel1.setMinimumSize(new java.awt.Dimension(840, 520));
        jPanel1.setPreferredSize(new java.awt.Dimension(840, 520));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("'nSECO PROJECT");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, 40));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setText("M2 A CONSTRUIR:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 44, -1, -1));

        txtMetros.setBackground(new java.awt.Color(51, 51, 51));
        txtMetros.setFont(new java.awt.Font("Dialog", 1, 52)); // NOI18N
        txtMetros.setForeground(new java.awt.Color(255, 19, 29));
        txtMetros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 153)));
        txtMetros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMetrosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMetrosKeyTyped(evt);
            }
        });
        jPanel1.add(txtMetros, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 76, 210, 60));

        btnJuntaTomada.setBackground(new java.awt.Color(153, 255, 153));
        btnJuntaTomada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnJuntaTomada.png"))); // NOI18N
        btnJuntaTomada.setBorder(null);
        btnJuntaTomada.setBorderPainted(false);
        btnJuntaTomada.setContentAreaFilled(false);
        btnJuntaTomada.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnJuntaTomada.setFocusPainted(false);
        btnJuntaTomada.setFocusable(false);
        btnJuntaTomada.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnJuntaTomadaRollOver.png"))); // NOI18N
        jPanel1.add(btnJuntaTomada, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 61, 129, 80));

        selectorJuntaTomada.setBackground(new java.awt.Color(51, 51, 51));
        selectorJuntaTomada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/selector.png"))); // NOI18N
        selectorJuntaTomada.setPreferredSize(new java.awt.Dimension(142, 92));
        jPanel1.add(selectorJuntaTomada, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 55, 142, -1));

        btnDesmontable.setBackground(new java.awt.Color(153, 255, 153));
        btnDesmontable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnDesmontable.png"))); // NOI18N
        btnDesmontable.setBorder(null);
        btnDesmontable.setBorderPainted(false);
        btnDesmontable.setContentAreaFilled(false);
        btnDesmontable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDesmontable.setFocusPainted(false);
        btnDesmontable.setFocusable(false);
        btnDesmontable.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnDesmontableRollOver.png"))); // NOI18N
        jPanel1.add(btnDesmontable, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 186, 129, 80));

        selectorDesmontable.setBackground(new java.awt.Color(51, 51, 51));
        selectorDesmontable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/selector.png"))); // NOI18N
        selectorDesmontable.setPreferredSize(new java.awt.Dimension(142, 92));
        jPanel1.add(selectorDesmontable, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 142, -1));

        btnSimple.setBackground(new java.awt.Color(153, 255, 153));
        btnSimple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnSimple.png"))); // NOI18N
        btnSimple.setBorder(null);
        btnSimple.setBorderPainted(false);
        btnSimple.setContentAreaFilled(false);
        btnSimple.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSimple.setFocusPainted(false);
        btnSimple.setFocusable(false);
        btnSimple.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnSimpleRollOver.png"))); // NOI18N
        jPanel1.add(btnSimple, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 61, 129, 80));

        selectorSimple.setBackground(new java.awt.Color(51, 51, 51));
        selectorSimple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/selector.png"))); // NOI18N
        selectorSimple.setPreferredSize(new java.awt.Dimension(142, 92));
        jPanel1.add(selectorSimple, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 55, 142, -1));

        btnDoble.setBackground(new java.awt.Color(153, 255, 153));
        btnDoble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnDoble.png"))); // NOI18N
        btnDoble.setBorder(null);
        btnDoble.setBorderPainted(false);
        btnDoble.setContentAreaFilled(false);
        btnDoble.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDoble.setFocusPainted(false);
        btnDoble.setFocusable(false);
        btnDoble.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnDobleRollOver.png"))); // NOI18N
        btnDoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDobleActionPerformed(evt);
            }
        });
        jPanel1.add(btnDoble, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 186, 129, 80));

        selectorDoble.setBackground(new java.awt.Color(51, 51, 51));
        selectorDoble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/selector.png"))); // NOI18N
        selectorDoble.setPreferredSize(new java.awt.Dimension(142, 92));
        jPanel1.add(selectorDoble, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 142, -1));

        btnMuros.setBackground(new java.awt.Color(153, 255, 153));
        btnMuros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnMuros.png"))); // NOI18N
        btnMuros.setBorder(null);
        btnMuros.setBorderPainted(false);
        btnMuros.setContentAreaFilled(false);
        btnMuros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMuros.setFocusPainted(false);
        btnMuros.setFocusable(false);
        btnMuros.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnMurosRollOver.png"))); // NOI18N
        jPanel1.add(btnMuros, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 186, 129, 80));

        selectorMuros.setBackground(new java.awt.Color(51, 51, 51));
        selectorMuros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/selector.png"))); // NOI18N
        selectorMuros.setPreferredSize(new java.awt.Dimension(142, 92));
        jPanel1.add(selectorMuros, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 142, -1));

        btnCielorrasos.setBackground(new java.awt.Color(153, 255, 153));
        btnCielorrasos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnCielorrasos.png"))); // NOI18N
        btnCielorrasos.setBorder(null);
        btnCielorrasos.setBorderPainted(false);
        btnCielorrasos.setContentAreaFilled(false);
        btnCielorrasos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCielorrasos.setFocusPainted(false);
        btnCielorrasos.setFocusable(false);
        btnCielorrasos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnCielorrasosRollOver.png"))); // NOI18N
        jPanel1.add(btnCielorrasos, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 61, 129, 80));

        selectorCielorrasos.setBackground(new java.awt.Color(51, 51, 51));
        selectorCielorrasos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/selector.png"))); // NOI18N
        selectorCielorrasos.setPreferredSize(new java.awt.Dimension(142, 92));
        jPanel1.add(selectorCielorrasos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 55, 142, -1));

        btnPlaca.setBackground(new java.awt.Color(153, 255, 153));
        btnPlaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btn0.6X0.6.png"))); // NOI18N
        btnPlaca.setBorder(null);
        btnPlaca.setBorderPainted(false);
        btnPlaca.setContentAreaFilled(false);
        btnPlaca.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPlaca.setFocusPainted(false);
        btnPlaca.setFocusable(false);
        btnPlaca.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btn0.6X0.6RollOver.png"))); // NOI18N
        btnPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlacaActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 316, 129, 80));

        selectorPlaca.setBackground(new java.awt.Color(51, 51, 51));
        selectorPlaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/selector.png"))); // NOI18N
        selectorPlaca.setPreferredSize(new java.awt.Dimension(142, 92));
        jPanel1.add(selectorPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 310, 142, -1));

        btnMinim.setBackground(new java.awt.Color(51, 51, 51));
        btnMinim.setForeground(new java.awt.Color(51, 51, 51));
        btnMinim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnMinizar.png"))); // NOI18N
        btnMinim.setBorder(null);
        btnMinim.setBorderPainted(false);
        btnMinim.setContentAreaFilled(false);
        btnMinim.setFocusPainted(false);
        btnMinim.setPreferredSize(new java.awt.Dimension(15, 15));
        btnMinim.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnMinizar.png"))); // NOI18N
        btnMinim.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnMinizar2.png"))); // NOI18N
        btnMinim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimActionPerformed(evt);
            }
        });
        jPanel1.add(btnMinim, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 3, 15, 15));

        btnCerrar2.setBackground(new java.awt.Color(51, 51, 51));
        btnCerrar2.setForeground(new java.awt.Color(51, 51, 51));
        btnCerrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnClose10x10.png"))); // NOI18N
        btnCerrar2.setBorder(null);
        btnCerrar2.setBorderPainted(false);
        btnCerrar2.setContentAreaFilled(false);
        btnCerrar2.setFocusPainted(false);
        btnCerrar2.setPreferredSize(new java.awt.Dimension(15, 15));
        btnCerrar2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnClose10x10.png"))); // NOI18N
        btnCerrar2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnClose.png"))); // NOI18N
        btnCerrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 3, 15, 15));

        btnCalcular.setBackground(new java.awt.Color(153, 255, 153));
        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnCalcular.png"))); // NOI18N
        btnCalcular.setBorder(null);
        btnCalcular.setBorderPainted(false);
        btnCalcular.setContentAreaFilled(false);
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCalcular.setFocusPainted(false);
        btnCalcular.setFocusable(false);
        btnCalcular.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnCalcularRollOver.png"))); // NOI18N
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 76, 160, 60));

        btnToPDF.setBackground(new java.awt.Color(153, 255, 153));
        btnToPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnToPDF.png"))); // NOI18N
        btnToPDF.setBorder(null);
        btnToPDF.setBorderPainted(false);
        btnToPDF.setContentAreaFilled(false);
        btnToPDF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnToPDF.setFocusPainted(false);
        btnToPDF.setFocusable(false);
        btnToPDF.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnToPDFRollOver.png"))); // NOI18N
        btnToPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToPDFActionPerformed(evt);
            }
        });
        jPanel1.add(btnToPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 458, 160, 40));

        btnPresupuesto.setBackground(new java.awt.Color(153, 255, 153));
        btnPresupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnCotizar.png"))); // NOI18N
        btnPresupuesto.setBorder(null);
        btnPresupuesto.setBorderPainted(false);
        btnPresupuesto.setContentAreaFilled(false);
        btnPresupuesto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPresupuesto.setFocusPainted(false);
        btnPresupuesto.setFocusable(false);
        btnPresupuesto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnpPresupRollOver.png"))); // NOI18N
        btnPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresupuestoActionPerformed(evt);
            }
        });
        jPanel1.add(btnPresupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 458, 160, 40));

        txtPresupuesto.setBackground(new java.awt.Color(204, 255, 204));
        txtPresupuesto.setColumns(20);
        txtPresupuesto.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        txtPresupuesto.setForeground(new java.awt.Color(51, 51, 51));
        txtPresupuesto.setRows(5);
        txtPresupuesto.setBorder(null);
        txtPresupuesto.setFocusable(false);
        jScrollPane2.setViewportView(txtPresupuesto);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 450, 290));

        lblPlaca.setFont(new java.awt.Font("Nirmala UI", 3, 9)); // NOI18N
        lblPlaca.setForeground(new java.awt.Color(153, 255, 153));
        lblPlaca.setText("PLACA 1,20x0,60 POR DEFECTO");
        jPanel1.add(lblPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 404, 160, -1));

        chkDesperdicio.setBackground(new java.awt.Color(51, 51, 51));
        chkDesperdicio.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        chkDesperdicio.setForeground(new java.awt.Color(153, 253, 153));
        chkDesperdicio.setText("DESPERDICIO 5%");
        chkDesperdicio.setBorder(null);
        chkDesperdicio.setContentAreaFilled(false);
        chkDesperdicio.setFocusPainted(false);
        chkDesperdicio.setFocusable(false);
        chkDesperdicio.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(chkDesperdicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 48, 160, -1));

        lblFirma.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        lblFirma.setForeground(new java.awt.Color(153, 255, 153));
        lblFirma.setText("DIP</>MU");
        jPanel1.add(lblFirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 501, 70, -1));

        jSeparator1.setBackground(new java.awt.Color(153, 255, 153));
        jSeparator1.setForeground(new java.awt.Color(153, 255, 153));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 438, 378, -1));

        lblUnidad.setFont(new java.awt.Font("Nirmala UI", 1, 52)); // NOI18N
        lblUnidad.setForeground(new java.awt.Color(153, 255, 153));
        lblUnidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUnidad.setText("TEXTO  $");
        lblUnidad.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lblUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 448, 340, 50));

        txtCantidad.setBackground(new java.awt.Color(51, 51, 51));
        txtCantidad.setFont(new java.awt.Font("Nirmala UI", 1, 56)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(255, 19, 29));
        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtCantidad.setToolTipText("ENTER para ingresar precio por unidad");
        txtCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 153)));
        txtCantidad.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCantidad.setPreferredSize(new java.awt.Dimension(48, 159));
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 129, 48));

        btnConfiguracion.setBackground(new java.awt.Color(153, 255, 153));
        btnConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnConfig.png"))); // NOI18N
        btnConfiguracion.setToolTipText("Acá podes configurar el nombre de tu emprendimiento");
        btnConfiguracion.setBorder(null);
        btnConfiguracion.setBorderPainted(false);
        btnConfiguracion.setContentAreaFilled(false);
        btnConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConfiguracion.setFocusPainted(false);
        btnConfiguracion.setFocusable(false);
        btnConfiguracion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesGUI/btnConfigRollOver.png"))); // NOI18N
        btnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 106, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDobleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDobleActionPerformed

    private void btnCerrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrar2ActionPerformed

    private void btnMinimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMinimActionPerformed

    private void btnPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlacaActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtMetrosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMetrosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMetrosKeyPressed

    private void txtMetrosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMetrosKeyTyped
     
    }//GEN-LAST:event_txtMetrosKeyTyped

    private void btnToPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToPDFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnToPDFActionPerformed

    private void btnPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresupuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPresupuestoActionPerformed

    private void txtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadKeyPressed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
       
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void btnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfiguracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_nSeco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_nSeco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_nSeco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_nSeco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_nSeco().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCalcular;
    public javax.swing.JButton btnCerrar2;
    public javax.swing.JButton btnCielorrasos;
    public javax.swing.JButton btnConfiguracion;
    public javax.swing.JButton btnDesmontable;
    public javax.swing.JButton btnDoble;
    public javax.swing.JButton btnJuntaTomada;
    public javax.swing.JButton btnMinim;
    public javax.swing.JButton btnMuros;
    public javax.swing.JButton btnPlaca;
    public javax.swing.JButton btnPresupuesto;
    public javax.swing.JButton btnSimple;
    public javax.swing.JButton btnToPDF;
    public javax.swing.JCheckBox chkDesperdicio;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lblFirma;
    public javax.swing.JLabel lblPlaca;
    public javax.swing.JLabel lblUnidad;
    public javax.swing.JLabel selectorCielorrasos;
    public javax.swing.JLabel selectorDesmontable;
    public javax.swing.JLabel selectorDoble;
    public javax.swing.JLabel selectorJuntaTomada;
    public javax.swing.JLabel selectorMuros;
    public javax.swing.JLabel selectorPlaca;
    public javax.swing.JLabel selectorSimple;
    public javax.swing.JTextField txtCantidad;
    public javax.swing.JTextField txtMetros;
    public javax.swing.JTextArea txtPresupuesto;
    // End of variables declaration//GEN-END:variables
}
